version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
    # Ajoute cette ligne pour spécifier l'utilisation de pipenv
    registries: {}
    open-pull-requests-limit: 10